version: "3"
services:
  redis:
    volumes:
      - ./data:/data
    build:
      context: ./redis
      dockerfile: Dockerfile.dev
    networks:
      - inner
    restart: always
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - redis
    networks:
      - inner
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
    networks:
      - inner
    restart: always

networks:
  inner:
